### save new person
POST http://localhost:8081/api/v1/persons
Content-Type: application/json
Accept: application/json


{
  "firstname": "Konstantin",
  "lastname": "Lantsov",
  "documents": [
    {
      "documentNumber": "MP3202487",
      "documentType": "PASSPORT"
    }
  ],
  "addresses": [
    {
      "country": "Belarus",
      "locality": "Minsk",
      "street": "Krasina",
      "houseNumber": 24,
      "apartmentsNumber": 79,
      "postcode": "220109",
      "addressType": "ACTUAL"
    }
  ],
  "contacts": [
    {
      "contactType": "PHONE_NUMBER",
      "contactValue": "+375447858303"
    },
    {
      "contactType": "EMAIL",
      "contactValue": "k.lantsov@yahoo.com"
    }
  ]
}



### get person info by uuid
GET http://localhost:8081/api/v1/persons/f64ad27b-dd81-4d60-a85b-add789e78628
Accept: application/json



### get all persons
GET http://localhost:8081/api/v1/persons
Accept: application/json



### verify person
GET http://localhost:8081/api/v1/persons/verify?lastname=Lantsov&documentType=PASSPORT&documentNumber=MP3202487
Accept: application/json